apiVersion: lambda.services.k8s.aws/v1alpha1
kind: FunctionURLConfig # kind is what this section of YAML will inact
metadata:
  name: url-config
spec:
  authType: NONE # NONE this allows for a public Function URL Endpoint, HOWEVER it's permissions are not set for you yet
  functionName: lambda-oci-ack # this is going to be the name of the service generated in AWS
--- # Breaking the yaml into another docu
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: lambda-oci-ack
  annotations:
    services.k8s.aws/region: us-east-1 # region your cluster is on
spec:
  name: lambda-oci-ack
  packageType: Image
  code:
    imageURI: 296271419447.dkr.ecr.us-east-1.amazonaws.com/lambda-get-items:latest
  role: arn:aws:iam::296271419447:role/ack-lambda-controller # IAM Role that we made
  description: function created by ACK lambda-controller e2e tests
  memorySize: 256 # Lambda Function needs more memory in order to boot the image and run
